### ISSUE TITLE
Windows support: no precommit hook being created

### ISSUE THREAD

**Issue by ConnerAiken** [BrainMaestro/composer-git-hooks#101]
Hi, 

This is probably something right in front of my face but I'm hoping someone can spot my error here.

We are trying to use `php-cs-fixer` in combination with `composer-git-hooks` to lint staged files on pre-commit. It is working fine in Ubuntu but not windows 10. I have tried every combination of actions to get it to work (clear composer.lock, remove vendor, reinstall repo from scratch, --force-win and --no-lock flags, everything).

Here is our composer.json
```
{
	"require-dev": { 
		"friendsofphp/php-cs-fixer": "^2.15",
		"brainmaestro/composer-git-hooks": "^2.8"
	},
	"require": {
                "php": "7.3.*",
		"ext-json": "*",
		"ext-curl": "*", 
	},
	"scripts": {
                "post-install-cmd": "php vendor/bin/cghooks add --force-win",
		"post-update-cmd": "php vendor/bin/cghooks update",
		"pre-commit": [ 
			"echo 'Linting all PHP files'",
			"php vendor/bin/php-cs-fixer fix . --verbose --config .php_cs",
			"git add -u"
		]
	} 
}

```

Here is sample output of `composer install` - happening on multiple windows machines
![image](https://user-images.githubusercontent.com/7544450/68052131-370ed380-fca6-11e9-9259-cf884a777ab3.png)

`vendor/bin/cghooks update` and `vendor/bin/cghooks add` produce the same result. No `.git/hooks/pre-commit` file.

Can anyone spot anything? Many thanks.

**Comment by ConnerAiken** [comment]
I resolved this with the following config..

```
	"scripts": {   
		"lint": "php-cs-fixer fix . --verbose --config .php_cs",
		"verify": "php-cs-fixer fix . --using-cache=no --dry-run --stop-on-violation --verbose --config .php_cs",
		"post-install-cmd": "cghooks add --ignore-lock",
		"post-update-cmd": "cghooks update",
		"pre-commit": [ 
			"echo 'Linting all modified PHP files'", 
			"composer lint",
			"echo 'Adding all modified PHP files to the commit'",
			"git add -u"
		]
	}```

**Comment by ConnerAiken** [comment]
Resolved.

**Comment by BrainMaestro** [comment]
Hey @ConnerAiken that's great. I was meaning to take a look at this today. Glad you solved it
