### ISSUE TITLE
Check composer config validation

### ISSUE THREAD

**Issue by jhoff** [BrainMaestro/composer-git-hooks#104]
This perhaps isn't an issue with the package more than a user experience issue, but if you modify your composer.json file and accidentally leave invalid markup ( say an extra comma at the end of an array ), then all of the `cghooks` commands either fail silently or say there's nothing to do.

Perhaps simply executing a `composer validate --no-check-lock` before each cghooks command would be sufficient?

**Comment by BrainMaestro** [comment]
Good idea. I think `composer validate --no-check-lock` wouldn't be a terrible solution btw. That way, we guarantee that not just the json is valid, but the entire composer schema is valid as well. It might have some unexpected effects though
