### ISSUE TITLE
Lazy hook evaluation

### ISSUE THREAD

**Issue by SamMousa** [BrainMaestro/composer-git-hooks#107]
I'm wondering why the users' hooks need to be installed? Instead you could just have 1 hook script that calls `cghooks` which can then read the `composer.json` and execute the actual hooks.

I understand why we need to install a hook in the git folder, I just don't understand why it needs to be the actual users' hook instead of a single gchooks wrapper.

**Comment by BrainMaestro** [comment]
@SamMousa I guess that's another approach, but I don't quite see what the benefit would be

**Comment by SamMousa** [comment]
Currently we always have to add a `post-install-cmd` and `post-update-cmd` hook to make sure any changes to our hooks are reflected in the git hooks.
This is not needed with my approach.

Note it could even be implemented simpler than I originally thought:
```
"scripts": {
    "pre-commit": [
        // Do something
    ],
    "post-merge": [
       // Do something
    ]    
},
"extra": {
    "hooks": {
        "pre-commit": "composer run pre-commit"
        "post-merge": "composer run post-merge"
    }
}

```

This would just require the hooks to be installed once and actual running would always run the latest things from composer.
FYI, I'm also looking into using a composer plugin to automate git hook installation.

**Comment by BrainMaestro** [comment]
Fair enough, that could work, but every time the hooks section of `composer.json` changes, the installed hooks would need to be updated as well. So you do still need `post-install-cmd` and `post-update-cmd`. Or do you see a way around that?

**Comment by SamMousa** [comment]
Yeah, we could remove the hooks section all together - they always execute the same: composer run {git event} . And we can (I think) auto install them by changing the composer type and providing a custom installer.

**Comment by BrainMaestro** [comment]
Okay, I think it's worth considering as hooking into composer more closely will also allow us to solve other issues with not having dev dependencies in production installs

**Comment by BrainMaestro** [comment]
I will close this for now due to inactivity, but if you have any ideas on how to proceed with this, let me know
