### ISSUE TITLE
Hook errors does not stop pre-commit hook with an error

### ISSUE THREAD

**Issue by bertrandjamin** [BrainMaestro/composer-git-hooks#108]
Hi, 
And first of all thanks for your job on this library 👍

--- 

I have this hook configuration :

```json
# composer.json
       "hooks": {
            "pre-commit": [
                "make cs.fixer.dryrun",
                "make test.phpstan",
                "make test.phpunit"
            ]
        }
```

```
# makefile
test.phpstan:
	docker-compose run etl vendor/bin/phpstan analyse -l8 src

test.phpunit:
	docker-compose run etl bin/phpunit

cs.fixer.dryrun:
	docker-compose run etl vendor/bin/php-cs-fixer -vvv fix --dry-run
```

This configuration creates the given pre-commit hook file : 
```
#!/bin/sh

make cs.fixer.dryrun
make test.phpstan
make test.phpunit
```

The problem is that if, for example, `make cs.fixer.dryrun` exit with an error it does not stop the pre-commit hook and the commit is validated.

In fact the only script wich could abort the commit is the last of the list.

--- 

AFAIK the '-e' option resolve this issue by exiting the script on the first error response from a line.
http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#The-Set-Builtin

--- 

Actually I have enforced this behaviour by adding a pre-commit line in my composer.json 

```
       "hooks": {
            "pre-commit": [
                "set -e",
                "make cs.fixer.dryrun",
                "make test.phpstan",
                "make test.phpunit"
            ]
        }
```

But I'm surprized that this behaviour is not the one defined by default? 
Did I miss something ? 

Thanks

**Comment by BrainMaestro** [comment]
Hi @bertrandjamin thanks for the detailed bug report. You're right, this seems like an oversight. `set -e` could be a choice, but it seems to have many drawbacks.[]. This specific issue was fixed in https://github.com/BrainMaestro/composer-git-hooks/pull/106, I was supposed to make a release, but other things came up. I will try to make a new release soon. You can use `dev-master` in the meantime to confirm that it has the expected behavior

**Comment by bertrandjamin** [comment]
Hi @BrainMaestro,

Thanks for your answer and for the link on the `-e`option drawbacks 👍 
I was not aware of those "complications" ^^

The `&&` solution seems perfect and I will use it right after your next release !

**Comment by Asenar** [comment]
Hi,

I strongly suggest to add in documentation than the hooks behaviour is not «usual» and in case of many hooks, pre hooks will pass.

the `&&` hack seems to fix the problem, but why not generate the hooks with something like `./command1 && ./command2 || exit 1` ?

**Comment by BrainMaestro** [comment]
A new release has been made which solves this. Feel free to reopen if it reoccurs

**Comment by Shohoo** [comment]
`"config": {
                "stop-on-failure": ["pre-commit"]
            },
            "pre-commit": [
                "echo committing as $(git config user.name)",
                "composer run phpstan",
                "composer run phpstan-generate-baseline"
            ]`

still passes
