### ISSUE TITLE
Adding unvalidated hooks (ex. Git Flow hooks)

### ISSUE THREAD

**Issue by micc83** [BrainMaestro/composer-git-hooks#109]
Hi, first of all thank you for the great package.

While trying to add a custom hook for Git Flow (https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-Hooks-and-Filters) I figured out that cghooks doesn't allows it as it validates hook names against a list of official git hooks before adding them:

https://github.com/BrainMaestro/composer-git-hooks/blob/676162c00a81f9751c89d83a44495f927defc44e/src/Hook.php#L33

So, what about adding a `--skip-validation` general option to `BrainMaestro\GitHooks\Commands\Command` to allow adding hooks even if not officially supported by git? I can obviously create a PR if you wish.

My only concern is about the call made on the main executable to implement test commands:

https://github.com/BrainMaestro/composer-git-hooks/blob/676162c00a81f9751c89d83a44495f927defc44e/cghooks#L32-L34

I don't see a clean way to pass the `--skip-validation` option to this call. We might just allow it to call all hooks if that doesn't concerns you.

What you think?

**Comment by BrainMaestro** [comment]
Hi @micc83. yes, I think this is a fine idea. I also don't mind updating that part to call all the hooks instead of only valid ones

**Comment by micc83** [comment]
Great. Shall I create the PR or will you?

**Comment by BrainMaestro** [comment]
If you can, please create one
