### ISSUE TITLE
Issue with multiline hook and &&

### ISSUE THREAD

**Issue by shaffe-fr** [BrainMaestro/composer-git-hooks#113]
Hi,
I have the following script that checks that a commit message is formatted properly:
```json
{
  "prepare-commit-msg": [
      "CUR_BRANCH=\"$(git branch | grep '*' | sed 's/* //')\"",
      "if [ \"$CUR_BRANCH\" = '(no branch)' ]; then",
      "  exit 0",
      "fi",
      "COMMIT_REGEX='^(fixup! )*?(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\\([a-z ]+\\))?: .+$'",
      "if ! grep -qE \"$COMMIT_REGEX\" \"$1\"; then",
      "  echo 'Invalid commit message, aborting... See https://github.com/pvdlg/conventional-changelog-metahub#commit-types' >&2",
      "  exit 1",
      "fi"
  ]
}
```

Since #106, multiline commands entries are now joined with `&& \`. That brokes the bash script.
As json doesn't allow multline strings, I don't see other way to write the script.
I find convenient to write these little scripts in composer.json directly and not in separate script files.

Any thoughts?
Thanks

**Comment by AnjaLiebermann** [comment]
I have the same problem and it drives me nuts. 

My script loooks like this and it worked perfectly until recently:

```
        "hooks": {
            "commit-msg": [
                "regex=\"^([A-Z]{2,5}-[0-9]{1,4}|(no-ticket|NO-TICKET)):[\\s]*.{10,}\"",
                "file=`cat $1`",
                "if ! [[ $file =~ $regex ]]; then",
                "  echo \"ERROR - Commit message is wrong or too short. E.g. AZ-33: Description or NO-TICKET: Description\"",
                "  exit 1",
                "fi"
            ],
```

Now I get the error message: 
```
$ bin/cghooks commit-msg
sh: -c: line 2: syntax error near unexpected token `&&'
sh: -c: line 2: `if ! [[ $file =~ $regex ]]; then && \'
```

**Comment by shaffe-fr** [comment]
The PR can be considered as a breaking. I think, it should be behind an optin flag for now.

**Comment by shaffe-fr** [comment]
For now @AnjaLiebermann, I fixed the package version in my composer.json: `"brainmaestro/composer-git-hooks": "2.8.3",`.

**Comment by shaffe-fr** [comment]
@BrainMaestro As it's breaking, would you be open to a PR to make the `&&` behaviour optionnal? 

We could maybe add a config object in the composer.json, to activate the commands sequences escape for for some or all hooks.
```jsonc
{
  "extra": {
    "hooks": {
        "config": {
            "comands": true, // if true, sequences of commands escape will be used for all hooks. Otherwise, the prior escape behaviour will be used
            // OR
            "comands": ["pre-push"] // array of hooks that should use the sequence of commands escaping
        }
    }
}
```
Any thoughts?

**Comment by BrainMaestro** [comment]
Hmm that sounds like a good idea. I like the second option. 

Also @shaffe-fr @AnjaLiebermann, apologies for the breakage. I will publish a new version with a revert for this feature

**Comment by shaffe-fr** [comment]
Thanks, I'll prepare a PR for the array syntax ASAP.

**Comment by BrainMaestro** [comment]
Fixed in #115. I'll give you both some time to try it out with dev-master before I make a new feature release. Feel free to reopen this if you have any issues

**Comment by shaffe-fr** [comment]
Hi @BrainMaestro, I've used #115 for some days, and encoutered no issues so far.

**Comment by shaffe-fr** [comment]
I'm encoutering some issues tonight. It not sure, but it might be related.

**Comment by shaffe-fr** [comment]
Forget what I said, it wasn't related to the #115 PR.
