### ISSUE TITLE
Make path to .git configurable

### ISSUE THREAD

**Issue by mzeis** [BrainMaestro/composer-git-hooks#2]
Thank you for this great tool!

Our `composer.json` is in another directory than the `.git/` directory. At the moment, the writing of hooks fails in this scenario.

Would it be okay for you to add an option like `--git-dir='/path/to/.git'` which lets one define another path than just `.git`?

**Comment by BrainMaestro** [comment]
Thanks!

Sure. I'll take a look at it. That's a good suggestion.

**Comment by BrainMaestro** [comment]
Hey @mzeis. `v0.3.0` should fix that issue. Let me know if you encounter any other issues.

**Comment by mzeis** [comment]
Works like a charme. Amazing response time, thank you again!

**Comment by BrainMaestro** [comment]
You're welcome

**Comment by FabianKoestring** [comment]
@mzeis - Is there a way to add the git-dir to composer.json ?
