### ISSUE TITLE
Missing symfony/process dependancy

### ISSUE THREAD

**Issue by kasparsd** [BrainMaestro/composer-git-hooks#24]
Introduced in #23.

https://github.com/BrainMaestro/composer-git-hooks/blob/d3ba750289d479a07d68d72b9b5afbad24ec1b03/src/helpers.php#L3

However, `symfony/process` is missing from `composer.json`:

https://github.com/BrainMaestro/composer-git-hooks/blob/d3ba750289d479a07d68d72b9b5afbad24ec1b03/composer.json#L18-L21

**Comment by BrainMaestro** [comment]
Yeah you're right. It wasn't picked up during development because `symfony/console` uses `symfony/process` as a dev dependency. I wonder if it's worth it to include a dependency for such a minor case. We can probably just use `shell_exec`

**Comment by joaorobertopb** [comment]
Hi guys!

My suggestion:

```php
if (! function_exists('git_version')) {
    /**
     * Get latest git tag version.
     *
     * @return string
     */
    function git_version()
    {
        $gitCommand = 'git describe --tags $(git rev-list --tags --max-count=1)';
        if (class_exists('Symfony\Component\Process\Process')) {
            $process = (new Process($gitCommand))->run();
            return trim($process->getOutput());
        }
        return trim(exec($gitCommand)); // Or shell_exec
    }
}
```

**Comment by BrainMaestro** [comment]
That's better, but now that I think about it, I'd prefer not to use git to determine this because the version should work on computers without git installed.

**Comment by joaorobertopb** [comment]
@BrainMaestro  OK no problems!

This function is not essential for the operation of the package, it can be removed if you prefer. :smile:

**Comment by BrainMaestro** [comment]
It was a good idea because I always forget to update the string, but oh well. Do you want to make a PR?

**Comment by joaorobertopb** [comment]
I can send a PR at night (my time zone is UTC -3, now it's 9:20 am here).
