### ISSUE TITLE
One command is no command

### ISSUE THREAD

**Issue by pretzlaw** [BrainMaestro/composer-git-hooks#38]
Currently everyone should write like this:

```
"extra": {
    "hooks": {
      "pre-commit": ""
    }
  }
```

But this is not supported:

```
"extra": {
    "hooks": {
      "pre-commit": [
            "but",
            "why?"
      ]
    }
  }
```

It totally makes sense to have more than one command there.

**Comment by BrainMaestro** [comment]
Yes it does. There was a PR recently to introduce that, but it had to be closed. Would you be interested in implementing it? It should be relatively easy to do.

**Comment by pretzlaw** [comment]
No, sorry. I tried but came up cleaning up all tests. I rather drop this and have a one-liner pointing to a bash than fixing this.

**Comment by BrainMaestro** [comment]
Do you want to take a look at the linked PR? It handles this rather nicely I think without changing much
