### ISSUE TITLE
Worktree support

### ISSUE THREAD

**Issue by daniert** [BrainMaestro/composer-git-hooks#54]
It would be nice to have worktree support: If you accidentally run (for example, within a "composer install" configuration) "cghooks update" (or similar) in a worktree dir, "file_put_contents" fails (there's no ".git" directory). It should detect if you are in a worktree and:
- Option 1: don't make any change
- Option 2: find the real .git and apply changes

**Comment by BrainMaestro** [comment]
Hi @daniert, yeah that's a good idea. Would you be interested in implementing? should be a relatively simple fix
