### ISSUE TITLE
customize hooks feature

### ISSUE THREAD

**Issue by liujingyu** [BrainMaestro/composer-git-hooks#6]
```
{
   ......
    "extra": {
        "hooks": {
            "cbf": "composer phpcbf app ext config database",
            "pre-commit": "composer phplint && composer --no-ansi phpcs -- --parallel=10 --standard=PSR2 -n --colors --encoding=utf-8 --report-diff=change.diff app config database ext",
            "post-commit": "php -r \"file_exists('./change.diff') && empty(trim(file_get_contents('./change.diff'))) && exec('rm ./change.diff');\" && echo committed",
            "pre-push": "composer phplint && echo pushing!"
        },
        "customize_hooks": ["cbf"]
    }
}
```

This my `composer.json` file. I want to adavance git hooks feature.

**Comment by BrainMaestro** [comment]
Hey @liujingyu. Composer has in-built [functionality](https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands) that makes this much easier. Take a look, and let me know how well it works out for you.

**Comment by liujingyu** [comment]
Thanks, I know.

**Comment by BrainMaestro** [comment]
So after thinking about it, I don't think this feature is a good fit for this project. I appreciate the contribution though. Thanks for taking the time. I'll close this, but if something comes up feel free to reopen.
