### ISSUE TITLE
Support PHP 7.3

### ISSUE THREAD

**Issue by apertureless** [BrainMaestro/composer-git-hooks#62]
Would be awesome if you could support PHP 7.3 
Right now the requirements are set to < 7.3 thus its not installable without the `--ignore-platform-reqs` arg.

```
brainmaestro/composer-git-hooks v2.6.0 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.3.0) does not satisfy that requirement.
```

**Comment by BrainMaestro** [comment]
@apertureless hmm, I'm not sure why that is even there. I'll remove it.

**Comment by deguif** [comment]
Is a new release planned for this? This is blocking our upgrade to PHP 7.3

**Comment by deguif** [comment]
Perfect, thanks @BrainMaestro

**Comment by BrainMaestro** [comment]
@apertureless @deguif can you check that master is installable from php 7.3?

**Comment by apertureless** [comment]
works for me :)

**Comment by BrainMaestro** [comment]
Okay that's great. I'll make a new release

**Comment by Geobusteni** [comment]
@BrainMaestro, it seems this issue surfaced again?

**Comment by BrainMaestro** [comment]
@Geobusteni what version are you installing? And what which version of PHP?

**Comment by Geobusteni** [comment]
Version 2.6.0 on PHP 7.3.5 ...

**Comment by BrainMaestro** [comment]
That version is from before this was fixed. Also it is really old (from 2018). Can you update to the latest?
