### ISSUE TITLE
Hooks on Windows environment

### ISSUE THREAD

**Issue by SuNflOw1991** [BrainMaestro/composer-git-hooks#7]
Hi,

thanks a lot for creating and sharing this amazing package.

I got stuck with a little issue and want you to ask for assistance. 
I'm running Composer on a windows box. I have installed `brainmaestro/composer-git-hooks` as recommended in the docs. If I run `./vendor/bin/cghooks pre-commit` everything works fine and as expected. But if I want to commit via git command `git commit -am 'Add feature xy.'` I get an error:  
```
error: cannot spawn .git/hooks/pre-commit: No such file or directory
```

Some research on this topic brought me to https://stackoverflow.com/a/20610055 with the suggestion to add the SHEBANG `#!/bin/bash` to the hook files. After adding this, everything works fine.

Is there a way (or could we have a way) to add this SHEBANG automatically to the hook files generated by `cghooks`?

My Composer file is looking as followed:
```json
{
    "scripts": {
        "csw": [
            "phpcs --standard=ruleset_psr2_win.xml --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers"
        ],
        "cs": [
            "phpcs --standard=psr2 --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers"
        ],
        "test": [
            "phpunit --coverage-text"
        ]
    },
    "extra": {
        "hooks": {
            "pre-commit": "composer csw",
            "pre-push": "composer test"
        }
    }
}
```

**Comment by BrainMaestro** [comment]
Hey @SuNflOw1991, glad to hear that you like the project. I didn't test on Windows, so the issue didn't come up. But sure, I'll fix it.

You are welcome to try. How I would do it is by checking the OS before creating the hook files and adding the SHEBANG if we're in Windows.

**Comment by SuNflOw1991** [comment]
Thanks a lot, I very appreciate your efforts.

The proposed solution sounds good to me. I will try it as soon as the update is ready.
