### ISSUE TITLE
Pass list of changed files as array variable

### ISSUE THREAD

**Issue by pretzlaw** [BrainMaestro/composer-git-hooks#76]
It would be great to fasten up things. Instead of

```
"pre-commit": [ "phpcs-foo" ]
```

(parsing hundreds of files) it could be 

```
"pre-commit": [ "phpcs-foo ${changedFiles[*]}" ]
```

rather an array than a string that is less flexible.
Passing this to the custom hooks can have multiple benefits but at least it speeds up things for static code analysis.
In addition the developer only gets rejected about things that he did "wrong" and not about some ignorant force push from other devs.

Is this possible right now or as a new feature?

**Comment by BrainMaestro** [comment]
Hey @pretzlaw, that sounds like a good idea, and might not be too hard to implement. do you want to give it a shot?

**Comment by glensc** [comment]
this variable is not available right now? or I'm mistaken? it needs to be built by executing some git commands.

a quick search gives maybe:
```
git diff-tree --no-commit-id --name-only HEAD
```

ref: https://stackoverflow.com/questions/424071/how-to-list-all-the-files-in-a-commit

**Comment by BrainMaestro** [comment]
Hi @glensc. I'm just seeing this now. That's pretty cool. @pretzlaw this should be good enough right? I'll just close this now

**Comment by pretzlaw** [comment]
Hm. No, this shows up some path where the (one) changed file is in. Not only the changed file. Anyhow, we see that this won't be added. Okay.

**Comment by BrainMaestro** [comment]
@pretzlaw I'm not sure I understand. Doesn't this solve the problem for you? you can also use
```sh
 git status --short | awk '{print $2}'
```
to list changed files that haven't been committed which would probably be more useful for a pre-commit hook.

**Comment by renzit** [comment]
for some reason 
this doesn't work
```git diff --name-only```

And this does work.
```git status --short```

**Comment by chriskaya** [comment]
Just to add my solution for this:
```
git diff --name-only --staged --diff-filter=d
```
`--diff-filter=d` allows me to filter out deleted files, so that I can do
```
git diff --name-only --staged --diff-filter=d | xargs git add -u
```
after linting without getting an annoying "fatal: pathspec 'xxx' did not match any files"

Reference: https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203
