### ISSUE TITLE
Composer could not find a composer.json file

### ISSUE THREAD

**Issue by aman00323** [BrainMaestro/composer-git-hooks#85]
@BrainMaestro After updating to 2.7 i have face issue for the following scenario.

Project root directory has git folder, Inside that root directory i have another folder which contains project and where composer located.

So now when pre commit hook fired then it gives error **Composer could not find a composer.json file** 

Also it is looking for composer.json in root folder of project where it is not located.
But it is located in another folder inside root directory

**Comment by BrainMaestro** [comment]
Hi @aman00323 was this working correctly before 2.7? That logic shouldn't have changed. Are you running the `cghooks` from the project folder or the root directory? 
Also, Is this project open source? can I see the structure myself?

**Comment by aman00323** [comment]
@BrainMaestro i am not sure it was working or not before 2.7. But here is my directory structure you can have look.

- RootFolderOfProject
   - .git
   - ProjectCode 
      - composer.json

Try this directory structure and you will get that error, Sorry project is not open source but as i have mention that is project directory structure.

I am running cghooks from the root directory then it gives me error **No hooks were added Try updating**

If i run the code inside ProjectFolder then also it gives me same output

I am running following command from ProjectFolder `./vendor/bin/cghooks add`

**Comment by BrainMaestro** [comment]
I just tested it, and running inside the project folder works correctly. Check your `.git/hooks` folder, the hooks were probably already added there.

**Comment by aman00323** [comment]
Yes, it is working. Need to change directory while running through composer. Actual code is

`"pre-commit": [
                "composer run lint"
            ]`

And i have changed it to 

`"hooks": {
            "pre-commit": [
                "cd app && composer run lint"
            ]
        }`

This might help to someone who is using same directory.

**Comment by BrainMaestro** [comment]
Oh I see the problem. The hooks are run from the same folder as the `.git` directory, so you might need to change the directory first like that. I'll just close this now
