### ISSUE TITLE
Hooks are installed in a `--absolute-git-dir` directory

### ISSUE THREAD

**Issue by Broutard** [BrainMaestro/composer-git-hooks#88]
My hooks are installed in a `--absolute-git-dir` directory ;)
```
ls -al
total 2055
drwxrwxrwx 1 root root  12288 Jun 19 15:21 .
drwxrwxrwx 1 root root   4096 Jun 19 11:50 ..
drwxrwxrwx 1 root root      0 Jun 19 15:21 --absolute-git-dir
drwxrwxrwx 1 root root      0 Jan 16 17:33 app
[...]
```

```
git --version
git version 2.11.0

git rev-parse --absolute-git-dir
--absolute-git-dir
```

It seems `--absolute-git-dir` was introduced in 2.13

_Originally posted by @Broutard in https://github.com/BrainMaestro/composer-git-hooks/pull/79#issuecomment-503562745_

**Comment by Broutard** [comment]
Note that `--git-dir` option works fine.

```
git rev-parse --git-dir
.git
```

**Comment by BrainMaestro** [comment]
That's unfortunate. Are you able to update your version of git? 
What does `git rev-parse --git-dir` show if you're in a nested directory?

**Comment by Broutard** [comment]
Yes, i'm able to update but v2.11 is the last Debian candidate version... so other people are going to have this issue too.

`git rev-parse --git-dir` return the absolute path if you are in a nested directory :

in my projet root:
```
git rev-parse --git-dir
.git
```

in a projet subdirectory
```
git rev-parse --git-dir
/var/www/myproject/.git
```

**Comment by BrainMaestro** [comment]
v2.11 is quite old though because the most recent is 2.21. Can you create a PR to switch to `--git-dir`?

**Comment by uqcgreen** [comment]
I'm getting the same behaviour, stuck using git 1.8 which I can't upgrade.

Rolling the version for this package back to 2.6 resolves the problem for now.

**Comment by aman00323** [comment]
@BrainMaestro we can do one thing when getting absolute directory at that time we will check git version on the based on version we will run the command to get directory.

I think for the older version we can use `git rev-parse --git-dir` also it is working for the new version of github 

Either we can use both command or use the old ones which will work for all the version

**Comment by aman00323** [comment]
@BrainMaestro we can do one thing when getting absolute directory at that time we will check git version on the based on version we will run the command to get directory.

I think for the older version we can use `git rev-parse --git-dir` also it is working for the new version of github 

Either we can use both command or use the old ones which will work for all the version

**Comment by BrainMaestro** [comment]
Yes we can just use the old one. I believe it should work. Can you make a PR? I won't be able to get to it right now

**Comment by aman00323** [comment]
@BrainMaestro Sure I will do that
