### ISSUE TITLE
Version 2.7.0 is R.I.P.

### ISSUE THREAD

**Issue by markokeeffe** [BrainMaestro/composer-git-hooks#90]
**Version 2.7.0 will execute `add` and `update` commands when composer `--no-dev` is provided, and skip the commands when in "dev mode"**

This commit: a46097f08b26944a899419978dacef62f6e53a2b implemented incorrect logic checking the composer "dev mode".

It contained this check (`src/Commands/AddCommand.php:49`): 
```php
        if (!$this->forceSetup && is_composer_dev_mode()) {
            // skip silently
            return;
        }
```  
that would silently skip executing the add or update commands when composer is in "dev mode".

Surely we want the commands to run in "dev mode", and by default, **not** run when the `--no-dev` flag is provided.

This could simply be fixed by changing the check to: 
```php
        if (!$this->forceSetup && is_composer_dev_mode() === false) {
            // skip silently
            return;
        }
```  

I can see that the commit was reverted here: 603989b6e2d1dc2c9a82ac16710626debf1998a4

But no new version has been created! **Anyone using version 2.7.0 will have the `add` and `update` commands silently skipped in "dev mode", and they will execute when the `--no-dev` flag is passed!**

At the very least, please create another tagged version after the revert commit 603989b6e2d1dc2c9a82ac16710626debf1998a4

**Comment by BrainMaestro** [comment]
HI @markokeeffe thanks for the heads up. I'll prepare a release shortly.

**Comment by BrainMaestro** [comment]
Done
