### ISSUE TITLE
[Question] How about to add option for lock file path?

### ISSUE THREAD

**Issue by hanovruslan** [BrainMaestro/composer-git-hooks#91]
[Question] How about to add option for lock file path?

Some projects has to have a lot of utility files like lock files and usually all of them are located in the project root. So why not to put cghooks.lock to some other place via cghooks binary option with project root by default?

**Comment by BrainMaestro** [comment]
Hmm not a bad idea @hanovruslan. Interested in implementing it?

**Comment by hanovruslan** [comment]
@BrainMaestro why not

**Comment by BrainMaestro** [comment]
Cool. Let me know if you need any assistance

**Comment by hanovruslan** [comment]
@BrainMaestro i dont understand what should i do with tests. I see a lot of failed test on my local machine

**Comment by hanovruslan** [comment]
@BrainMaestro Hi! is it possible to release this feature #92 as fix or minor release?

**Comment by BrainMaestro** [comment]
Hi @hanovruslan, yes, I will do that this weekend probably as `2.8.0`. It works if you install as `dev-master` right?

**Comment by hanovruslan** [comment]
> Hi @hanovruslan, yes, I will do that this weekend probably as `2.8.0`. It works if you install as `dev-master` right?

no, im not in a hurry ) just wonder

**Comment by BrainMaestro** [comment]
@hanovruslan it's released! Please reopen if you encounter any issues
