### ISSUE TITLE
Class 'CakeException' not found

### ISSUE THREAD

**Issue by piranna** [BrainMaestro/composer-git-hooks#93]
I'm new to `composer-git-hooks`, and not an expert in PHP, so this error annoys me a bit. When installing the dependencies with `./composer.phar install`, everything goes fine until try to install the git hooks:

```
> Vendor/bin/cghooks add --ignore-lock
PHP Fatal error:  Class 'CakeException' not found in /home/piranna/Trabajo/Prior/whitelabel-server/Plugin/JwtAuth/Controller/Component/Auth/TokenExpiredException.php on line 2
Script Vendor/bin/cghooks add --ignore-lock handling the post-install-cmd event returned with error code 255
```

How can I fix it? And how can an unrelated code on my project afect the git hooks install step?

**Comment by aman00323** [comment]
As you have mention in your snippet, the line which is throwing error it is not belong to `composer-git-hooks`, error is throwing inside your code.

see this `PHP Fatal error:  Class 'CakeException' not found in /home/piranna/Trabajo/Prior/whitelabel-server/Plugin/JwtAuth/Controller/Component/Auth/TokenExpiredException.php on line 2`

try to install package in fresh installation further, you need to provide more details so i can help you out.

**Comment by BrainMaestro** [comment]
@piranna do you still have this issue?

**Comment by piranna** [comment]
I'm not working on this project anymore, so I can't confirm...

**Comment by BrainMaestro** [comment]
Okay, then I will just close this, but if you have this issue again, feel free to reopen

**Comment by piranna** [comment]
Thank you.
