### ISSUE TITLE
Syntax error: word unexpected

### ISSUE THREAD

**Issue by ricardoboss** [BrainMaestro/composer-git-hooks#99]
Hi there! First of all: great tool! I love to keep the setup of repositories simple and having the ability to set up git hooks via composer is just great!

I recently ran into this problem and can't seem to figure it out on my own. I did the following and got this error:

```bash
$ vendor/bin/cghooks update
: not foundcghooks: 2: vendor/bin/cghooks:
: not foundcghooks: 4: vendor/bin/cghooks:
vendor/bin/cghooks: 6: vendor/bin/cghooks: Syntax error: word unexpected (expecting "in")
```

Any ideas? I don't really know what information can be useful so you'll have to tell me. Thanks!

**Comment by ricardoboss** [comment]
Running cghooks via composer (which it is in my setup) after a `composer update` results in:

```bash
$ composer exec -- cghooks update
Script cghooks handling the __exec_command event returned with error code 2
```

**Comment by BrainMaestro** [comment]
@ricardoboss thanks for the nice words. What version are you running?

**Comment by ricardoboss** [comment]
I'm currently using version 2.8.1

**Comment by BrainMaestro** [comment]
Alright, and  I forgot to ask what version of PHP. Is it possible to create a simple reproducible repo with this error? That would help a lot.

**Comment by ricardoboss** [comment]
My bad, it's PHP 7.3.10:

```bash
$ php -version
PHP 7.3.10-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct  8 2019 05:33:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.10-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

I'm running this in WSL (Windows Subsystem for Linux) on Ubuntu if that is relevant in any case. I'll try to come up with a repo that reproduces the error.

**Comment by ricardoboss** [comment]
So I created a clean git repository and installed `composer-git-hooks`. I then set up the following `composer.json`:

```composer.json
{
    "name": "ricardoboss/cghooks",
    "require": {
        "brainmaestro/composer-git-hooks": "^2.8"
    },
    "extra": {
        "hooks": {
            "pre-commit": [
                "echo 'pre commit!' >> git.log"
            ],
            "pre-push": [
                "echo 'pre push!' >> git.log"
            ],
            "post-merge": [
                "composer update",
                "echo 'post merge!' >> git.log"
            ]
        }
    },
    "scripts": {
        "post-install-cmd": [
            "composer exec -- cghooks add --ignore-lock || exit 0"
        ],
        "post-update-cmd": [
            "composer exec -- cghooks update"
        ],
        "setup": [
            "composer exec -- cghooks add --ignore-lock || exit 0"
        ]
    }
}
```

The composer scripts are the same as in the repository in which the error occurs.

---

Now in the original repository I tinkered a bit and found that this fixed it: I deleted the `vendor` folder and all custom git hooks from `.git/hooks/`. I then ran `composer install --no-cache` and at the end `composer exec -- cghooks add --ignore-lock || exit 0` exited clean; no more errors!

I usually use the terminal (which I set to use `wsl.exe`) inside PhpStorm in addition to the mostly helpful links provided by PhpStorm itself (like when you edit the `composer.json` it shows a link to install or update the packages). My guess is that PhpStorm and WSL, while both using composer, handle some things differently.

I don't know exactly what the problem was, but I executed all the steps above from WSL and it worked. Therefore, I'll close this issue, but if anyone else stumbles upon this error and my solution doesn't fix it, I'll reopen it.

**Comment by BrainMaestro** [comment]
Hi @ricardoboss thanks for the detailed response. This seems to be some strange behavior caused by running `cghooks` inside WSL and outside as well. And if someone stumbles on it, we'll tackle it again like you said
